### ISSUE TITLE
AGA SAVAŞLARI adı altında bir bildirim geldi.

### ISSUE THREAD

**Issue by DomatesGames** [KALITRIK/AGA-SAVASLARI#1]
Eğer kirletiyorsam özür dilerim silerim ama reponun ismi mükemmel:
AGA SAVAŞLARI

**Comment by Salih-Berat** [comment]
xd yakında oyunu güzelce geliştireceğiz şu anda C# falan güzelce öğreniyoruz
bu arada gereksiz issue açmayalım.
